services:
  devhabit.api:
    image: ${DOCKER_REGISTRY-}devhabitapi
    build:
      context: .
      dockerfile: DevHabit.Api/Dockerfile
    ports:
      - 5000:8080
      - 5001:8081
    environment:
      #设置导出遥测数据到哪里，可选下列两个服务的任意一个
      # Seq
      #- OTEL_EXPORTER_OTLP_ENDPOINT=http://devhabit.seq:5341/ingest/otlp
      #- OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      # Aspire Dashboard
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://devhabit.aspire-dashboard:18889
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc

  devhabit.seq:
    image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/datalust/seq:2025.2
    environment:
      ACCEPT_EULA: "Y"
      SEQ_FIRSTRUN_ADMINPASSWORD: "654321@qq.com"
    volumes:
      - ./.containers/seq_data:/data
    ports:
      - 8080:80
      - 5341:5341

  devhabit.aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:latest
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: true
    ports:
      - 18888:18888